name: Build ARM Firmware
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ARM GCC toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi
      - name: Install build tools
        run: |
          sudo apt-get install -y make cmake
      - name: Initialize submodules
        run: |
          git submodule update --init --recursive
      - name: Verify toolchain installation
        run: |
          arm-none-eabi-gcc --version
          make --version
          cmake --version
      - name: Create build directory
        run: |
          cd firmware
          mkdir build
      - name: Configure with CMake
        run: |
          cd firmware/build
          cmake ..
      - name: Build firmware
        run: |
          cd firmware/build
          make
